/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import DAO.NhanVienDAO;
import java.awt.Color;
import javax.mail.internet.AddressException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import utils.XEmail;
import utils.XImage;
public class DoiMatKhauKhiQuenJDialog extends javax.swing.JDialog {

    String emailNhanVien = null;
    
    public DoiMatKhauKhiQuenJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    private void init() {
        setLocationRelativeTo(null);
        setTitle("EduSys - Đổi Mật Khẩu");
        setIconImage(XImage.getAppIcon());
    }
    
    public DoiMatKhauKhiQuenJDialog(java.awt.Frame parent, boolean modal, String email){
        super(parent, modal);
        initComponents();
        init();
        emailNhanVien = email;
        thongBaoDoiMatKhau();
    }
    
    private void thongBaoDoiMatKhau() {
        if(nvDAO.selectByEmail(emailNhanVien) != null) {
            try {
                XEmail.sendSingleMail("Có vẻ như ai đó đã thay đổi mật khẩu EduSYS của bạn!", "hãy chắn chắc bạn là người đổi mật khẩu\n"
                        + "nếu không hãy liên hệ trưởng phòng để được hướng dẫn!", emailNhanVien);
            } catch (Exception e) {
            }
        }
    }
    
    NhanVienDAO nvDAO = new NhanVienDAO();

    private boolean isValidationForm() {
        StringBuilder strb = new StringBuilder();
        if(String.valueOf(txtnewPassword.getPassword()).isEmpty() || String.valueOf(txtnewPassword.getPassword()).trim().length()==0) 
            strb.append("Mật khẩu mới không được để trống!\n");
               
        if(String.valueOf(txtconfirmPassword.getPassword()).isEmpty() || String.valueOf(txtconfirmPassword.getPassword()).trim().length()==0) 
            strb.append("Vui lòng nhập lại mật khẩu!\n");

        if(!(String.valueOf(txtconfirmPassword.getPassword()).equals(String.valueOf(txtnewPassword.getPassword())))) 
            strb.append("Mật khẩu và nhập lại mật khẩu phải trùng!");
        
        if(strb.length()>0) {
            JOptionPane.showMessageDialog(this, strb);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        panelEmail1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtnewPassword = new javax.swing.JPasswordField();
        panelPassword = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtconfirmPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JPanel();
        btnTakePassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 144, 234));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi Mật Khẩu");

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(376, 300));

        panelEmail1.setBackground(new java.awt.Color(255, 255, 255));
        panelEmail1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(195, 195, 195), 2, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 144, 234));
        jLabel7.setText("Mật Khẩu Mới");

        txtnewPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtnewPassword.setBorder(null);

        javax.swing.GroupLayout panelEmail1Layout = new javax.swing.GroupLayout(panelEmail1);
        panelEmail1.setLayout(panelEmail1Layout);
        panelEmail1Layout.setHorizontalGroup(
            panelEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmail1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtnewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panelEmail1Layout.setVerticalGroup(
            panelEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtnewPassword)
        );

        panelPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(195, 195, 195), 2, true));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(19, 144, 234));
        jLabel8.setText("Nhập Lại");

        txtconfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtconfirmPassword.setBorder(null);
        txtconfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtconfirmPasswordMouseClicked(evt);
            }
        });
        txtconfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(49, 49, 49)
                .addComponent(txtconfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnLogin.setBackground(new java.awt.Color(19, 144, 234));
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 144, 234)));
        btnLogin.setPreferredSize(new java.awt.Dimension(205, 35));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
        });

        btnTakePassword.setBackground(new java.awt.Color(255, 255, 255));
        btnTakePassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTakePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnTakePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTakePassword.setText("Đặt Lại Mật Khẩu");
        btnTakePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTakePasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTakePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTakePasswordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTakePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTakePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(panelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtconfirmPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtconfirmPasswordMouseClicked
        Border border = BorderFactory.createLineBorder(new Color(19,144,234), 2);
        panelPassword.setBorder(border);
        border = BorderFactory.createLineBorder(new Color(187,187,187), 2);
        panelEmail1.setBorder(border);
    }//GEN-LAST:event_txtconfirmPasswordMouseClicked

    private void txtconfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmPasswordActionPerformed

    private void btnTakePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTakePasswordMouseClicked
        Border border = BorderFactory.createLineBorder(new Color(187,187,187), 2);
        panelEmail1.setBorder(border);
        panelPassword.setBorder(border);

        //xử lý code
        
        if(isValidationForm()) {
            nvDAO.updatePassword(new String(txtconfirmPassword.getPassword()), emailNhanVien);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
            this.dispose();
            new DangNhapJDialog(null, true).setVisible(true);
        }

    }//GEN-LAST:event_btnTakePasswordMouseClicked

    private void btnTakePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTakePasswordMouseEntered
        //hover button Login
        btnLogin.setBackground(Color.WHITE);
        Border border = BorderFactory.createLineBorder(new Color(19,144,234), 1);
        btnLogin.setBorder(border);
        btnTakePassword.setForeground(new Color(19,144,234));
    }//GEN-LAST:event_btnTakePasswordMouseEntered

    private void btnTakePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTakePasswordMouseExited
        //hover button Login
        btnLogin.setBackground(new Color(19,144,234));
        Border border = BorderFactory.createLineBorder(new Color(19,144,234), 1);
        btnLogin.setBorder(border);
        btnTakePassword.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnTakePasswordMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked

    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered

    }//GEN-LAST:event_btnLoginMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauKhiQuenJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauKhiQuenJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauKhiQuenJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauKhiQuenJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhauKhiQuenJDialog dialog = new DoiMatKhauKhiQuenJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel btnTakePassword;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelEmail1;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPasswordField txtconfirmPassword;
    private javax.swing.JPasswordField txtnewPassword;
    // End of variables declaration//GEN-END:variables
}
